version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_IMPORT=/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-realm/realm-export.json:/opt/keycloak/data/import/realm-export.json
    command:
      - start-dev
      - --import-realm
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - KEYCLOAK_URL=http://keycloak:8080/realms/basic-vote-realm
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID=basic-vote
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET=MdvMILu8Csm85tUnYzJdMuXjCZBTrato
    volumes:
      - ./logs:/app/logs
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
